apiVersion: v1
kind: Namespace
metadata:
  name: lab6
spec: {}
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
  namespace: lab6
  labels:
    typ: proxy
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-proxy
        image: nginx:1.19
        ports:
        - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
